# Generated by Django 4.1.3 on 2022-11-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitudejournal',
            name='journal_entry',
            field=models.TextField(help_text="Enter your Today's Journal Entry"),
        ),
    ]
