# Generated by Django 4.1.3 on 2022-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0002_alter_gratitudejournal_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitudejournal',
            name='date_created',
            field=models.DateField(),
        ),
    ]
