# Generated by Django 4.1.3 on 2022-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0006_alter_gratitudejournal_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitudejournal',
            name='positive_experience',
            field=models.TextField(blank=True, help_text='Share 1 positve experience which you experienced in past 24 Hours'),
        ),
    ]
