# Generated by Django 4.1.3 on 2022-11-09 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0007_gratitudejournal_positive_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attach_added', models.DateField(default=datetime.date.today)),
                ('gratitude_attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_attach', to='gratitudejournal.gratitudejournal')),
                ('life_log_attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_log_attach', to='gratitudejournal.gratitudejournal')),
                ('prescription_attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_attach', to='gratitudejournal.gratitudejournal')),
            ],
        ),
    ]
