# Generated by Django 4.1.3 on 2022-11-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0010_lifelog_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='date_attach_added',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='life_log_attach',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='life_log_attach_img',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='prescrip_attach_img',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='prescription_attach',
        ),
        migrations.DeleteModel(
            name='LifeLog',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
