# Generated by Django 4.1.3 on 2022-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0011_remove_attachment_date_attach_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='grat_attach_img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
