# Generated by Django 4.1.3 on 2022-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0013_alter_attachment_grat_attach_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='grat_attach_img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
