# Generated by Django 4.1.3 on 2022-11-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0015_alter_attachment_grat_attach_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeLogJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='lifelog_attach_image',
            field=models.ImageField(blank=True, upload_to='life_log_upload/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='grat_attach_img',
            field=models.ImageField(blank=True, upload_to='gratitude_upload/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='lifelog_attach_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_log_attach', to='gratitudejournal.lifelogjournal'),
        ),
    ]
