# Generated by Django 4.1.3 on 2022-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0017_gratitudejournal_images_delete_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitudejournal',
            name='journal_type',
            field=models.CharField(blank=True, choices=[('GJ', 'Gratitude Journal'), ('LJ', 'LifeLog Journal')], help_text='Select the Type of Journal', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gratitudejournal',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
