# Generated by Django 4.1.3 on 2022-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0018_gratitudejournal_journal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitudejournal',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
