# Generated by Django 4.1.3 on 2022-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudejournal', '0019_gratitudejournal_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitudejournal',
            name='journal_type',
            field=models.CharField(blank=True, choices=[('gratitude_journal', 'Gratitude Journal'), ('lifelog_journal', 'LifeLog Journal')], help_text='Select the Type of Journal', max_length=20, null=True),
        ),
    ]
